# Generated by Django 5.2 on 2025-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dare_modeifies",
        ),
        migrations.AddField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
