# Generated by Django 5.2 on 2025-05-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_reviewcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="reading_status",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("want_to_read", "Want to Read"),
                    ("currently_reading", "Currently Reading"),
                    ("dnf", "Did Not Finish"),
                ],
                default="read",
                max_length=20,
                verbose_name="Reading Status",
            ),
        ),
    ]
