# Generated by Django 5.2 on 2025-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_order_shipped_alter_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
