# Generated by Django 5.2 on 2025-04-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_paymentcard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentCard",
        ),
    ]
