# Generated by Django 5.2 on 2025-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_shippingaddress_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card Payment"), ("cod", "Cash on Delivery")],
                default="card",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_cvv",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
