# Generated by Django 5.2 on 2025-05-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_payment_payment_method_alter_payment_card_cvv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="payment.order",
            ),
        ),
    ]
