# Generated by Django 5.2 on 2025-05-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_payment_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="card_name",
            new_name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="card_cvv",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="card_expiry",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="card_number",
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("razorpay", "Razorpay")], default="razorpay", max_length=20
            ),
        ),
    ]
