# Generated by Django 5.2 on 2025-05-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_alter_payment_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="razorpay_order_id",
            new_name="card_name",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="card_cvv",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card Payment"), ("cod", "Cash on Delivery")],
                default="card",
                max_length=10,
            ),
        ),
    ]
